
---
sudo: false
language: ruby
cache: bundler
matrix:
  include:
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=6.x LOGSTASH_PATH=../../logstash ENV_SCHEMA=simple
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=master LOGSTASH_PATH=../../logstash ENV_SCHEMA=simple
  fast_finish: true
install: true
script: ci/bin/build.sh
jdk: openjdk8
