
---
sudo: false
language: ruby
cache: bundler
matrix:
  include:
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=6.x
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=master
  fast_finish: true
install: true
script: ci/bin/build.sh
jdk: oraclejdk8
