# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('javax.mail', 'javax.mail-api', '1.5.1')
require_jar('com.google.guava', 'guava', '16.0.1')
require_jar('com.googlecode.libphonenumber', 'libphonenumber', '8.0.0')
require_jar('com.github.fge', 'msg-simple', '1.1')
require_jar('com.github.fge', 'btf', '1.2')
require_jar('com.github.fge', 'uri-template', '0.9')
require_jar('com.github.java-json-tools', 'jackson-coreutils', '1.9')
require_jar('com.github.java-json-tools', 'json-schema-core', '1.2.10')
require_jar('com.github.java-json-tools', 'json-schema-validator', '2.2.10')
require_jar('org.logstash.plugins.input.http', 'logstash-filter-schema_validation', '0.2.0')
